import { motion } from 'motion/react';
import { 
  UserPlus, Fingerprint, Search, Calendar, FileText, ShoppingCart, 
  MapPin, MessageSquare, History, Bell, Star, ArrowRight, Smartphone 
} from 'lucide-react';
import { ActivePage } from '../types';

interface ForPatientsProps {
  setActivePage: (page: ActivePage) => void;
}

export default function ForPatients({ setActivePage }: ForPatientsProps) {
  const patientFeatures = [
    {
      icon: <UserPlus className="h-6 w-6" />,
      title: 'Simple Registration',
      description: 'Sign up in under 2 minutes. Store your key demographics and health parameters securely.',
    },
    {
      icon: <Fingerprint className="h-6 w-6" />,
      title: 'Biometric Secure Login',
      description: 'Access medical charts instantaneously using FaceID, TouchID, or pin authentication.',
    },
    {
      icon: <Search className="h-6 w-6" />,
      title: 'Global Medicine Search',
      description: 'Search hundreds of certified partner pharmacies near you for OTC or prescription products.',
    },
    {
      icon: <Calendar className="h-6 w-6" />,
      title: 'Flexible Consultations',
      description: 'Book immediate on-demand general consults or schedule specialists via secure text, voice, or video.',
    },
    {
      icon: <FileText className="h-6 w-6" />,
      title: 'Digital Prescriptions',
      description: 'Access real-time scripts generated by CareLoop doctors, instantly syncable to dispatch orders.',
    },
    {
      icon: <ShoppingCart className="h-6 w-6" />,
      title: 'Streamlined Basket Checkout',
      description: 'Consolidate multiple medicine orders, add coupons, and complete transactions with secure payment gateways.',
    },
    {
      icon: <MapPin className="h-6 w-6" />,
      title: 'Live Map Order Tracking',
      description: 'Track your prescription packages from pharmacy preparation to courier door-delivery with active GPS.',
    },
    {
      icon: <MessageSquare className="h-6 w-6" />,
      title: 'Pharmacist Live Chat',
      description: 'Consult directly with preparing pharmacists via encrypted chat for queries, substitutes, or side effects.',
    },
    {
      icon: <History className="h-6 w-6" />,
      title: 'Detailed Care History',
      description: 'Instantly view past consult records, medical bills, order statements, and reorder previous packages in one tap.',
    },
    {
      icon: <Bell className="h-6 w-6" />,
      title: 'Smart Push Reminders',
      description: 'Receive pill timings, appointment schedules, delivery dispatch updates, and medicine reorder alerts.',
    },
    {
      icon: <Star className="h-6 w-6" />,
      title: 'Reviews & Doctor Ratings',
      description: 'Share your care experience, rate healthcare professionals, and view authentic community-reviewed ratings.',
    },
  ];

  const journeySteps = [
    {
      number: '01',
      title: 'Describe & Search',
      description: 'Select your symptoms or specify the medication you need. Our system queries verified local partners and clinics.',
    },
    {
      number: '02',
      title: 'Consult virtually',
      description: 'Connect with a certified clinician via text, voice, or HD video. Obtain clinical assessments and a certified digital prescription.',
    },
    {
      number: '03',
      title: 'Express Delivery',
      description: 'Our partner pharmacy fulfills the script. A CareLoop GPS-tracked courier delivers your secure package in under 2 hours.',
    },
  ];

  return (
    <div id="for-patients-page" className="space-y-0">
      
      {/* 1. HERO SECTION */}
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-28 bg-gradient-to-br from-primary via-primary/95 to-secondary text-white overflow-hidden">
        <div className="absolute top-[-100px] right-[-100px] w-80 h-80 bg-white/5 rounded-full blur-3xl" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative text-center max-w-4xl">
          <motion.div
            initial={{ opacity: 0, y: -25 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="inline-block bg-white/10 text-green-400 font-semibold text-xs uppercase tracking-widest px-4 py-1.5 rounded-full border border-white/10 mb-6"
          >
            Empowering Your Health Journey
          </motion.div>
          
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="text-4xl sm:text-5xl md:text-6xl font-heading font-extrabold tracking-tight mb-6"
          >
            Healthcare Tailored to <br className="hidden md:inline" />
            <span className="text-green-400">Your Modern Life.</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="text-white/85 text-base md:text-lg max-w-2xl mx-auto leading-relaxed font-sans font-light"
          >
            Say goodbye to endless clinic waiting rooms and pharmacy pickup queues. CareLoop puts certified doctors, digital health records, and 2-hour home prescription deliveries directly in your pocket.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="pt-8 flex flex-wrap justify-center gap-4"
          >
            <button
              onClick={() => {
                setActivePage('contact');
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }}
              className="px-8 py-3.5 bg-green-400 text-secondary font-bold rounded-full hover:bg-white hover:text-primary transition-all duration-300 shadow-md cursor-pointer"
            >
              Get Free Patient Account
            </button>
          </motion.div>
        </div>
      </section>

      {/* 2. PATIENT FEATURES */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
            <h2 className="text-xs md:text-sm font-bold tracking-widest text-primary uppercase">
              Core Capabilities
            </h2>
            <p className="text-3xl md:text-4xl font-heading font-extrabold text-secondary tracking-tight">
              Features Built Around Your Wellness
            </p>
            <p className="text-secondary/60 text-sm md:text-base font-sans max-w-xl mx-auto">
              Our patient-centric mobile experience is integrated with standard-of-care tools for full peace of mind.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {patientFeatures.map((feature, idx) => (
              <motion.div
                key={idx}
                whileInView={{ opacity: 1, y: 0 }}
                initial={{ opacity: 0, y: 30 }}
                viewport={{ once: true, margin: '-50px' }}
                transition={{ duration: 0.4, delay: (idx % 3) * 0.1 }}
                className="bg-surface rounded-3xl p-6 border border-gray-100 hover:border-primary/20 shadow-sm hover:shadow-md transition-all duration-300 flex flex-col items-start text-left group"
              >
                <div className="p-3 bg-primary/10 rounded-xl text-primary mb-5 group-hover:bg-primary group-hover:text-white transition-colors duration-300">
                  {feature.icon}
                </div>
                <h3 className="font-heading font-bold text-lg text-secondary mb-2">
                  {feature.title}
                </h3>
                <p className="text-secondary/70 font-sans text-xs md:text-sm leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>

        </div>
      </section>

      {/* 3. VISUAL FLOW JOURNEY */}
      <section className="py-20 bg-surface">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-3">
            <h2 className="text-xs md:text-sm font-bold tracking-widest text-primary uppercase">
              The Journey
            </h2>
            <p className="text-3xl md:text-4xl font-heading font-extrabold text-secondary tracking-tight">
              Seamless Patient Experience Flow
            </p>
            <p className="text-secondary/60 text-sm md:text-base font-sans max-w-xl mx-auto">
              How CareLoop delivers virtual clinical diagnostics and physical medication in minutes.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 relative">
            {/* Visual connector bar on desktop */}
            <div className="hidden lg:block absolute top-[100px] left-1/6 right-1/6 h-0.5 bg-gradient-to-r from-primary/10 via-primary/30 to-primary/10 -z-1" />

            {journeySteps.map((step, index) => (
              <div
                key={index}
                className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm flex flex-col justify-between hover:shadow-md transition-all duration-300 relative text-left"
              >
                <div>
                  <div className="flex items-center justify-between mb-6">
                    <span className="text-4xl font-heading font-black text-primary/15 tracking-tight">
                      {step.number}
                    </span>
                    <span className="w-8 h-8 rounded-full bg-primary/5 text-primary text-xs font-bold flex items-center justify-center">
                      ✓
                    </span>
                  </div>
                  <h3 className="font-heading font-bold text-xl text-secondary mb-3">
                    {step.title}
                  </h3>
                  <p className="text-secondary/70 text-sm font-sans leading-relaxed">
                    {step.description}
                  </p>
                </div>
                <div className="pt-6 mt-6 border-t border-gray-50 flex items-center text-xs text-primary font-semibold">
                  <span>100% Secure & Private</span>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* 4. DOWNLOAD CTA */}
      <section className="py-20 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-gradient-to-br from-primary to-secondary rounded-3xl p-8 md:p-12 text-white text-center space-y-6 shadow-lg relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full blur-2xl" />
            
            <Smartphone className="h-12 w-12 text-green-400 mx-auto" />
            <h2 className="text-2xl md:text-4xl font-heading font-extrabold">
              Get Started with CareLoop Today
            </h2>
            <p className="text-white/80 font-sans text-sm md:text-base max-w-xl mx-auto leading-relaxed">
              Join our connected loop. Download the app, secure your demographic medical details, and speak with a licensed on-call doctor in seconds.
            </p>
            <div className="pt-4 flex justify-center">
              <button
                onClick={() => {
                  setActivePage('contact');
                  window.scrollTo({ top: 0, behavior: 'smooth' });
                }}
                className="inline-flex items-center justify-center px-8 py-3.5 bg-green-400 text-secondary font-bold rounded-full hover:bg-white hover:text-primary hover:scale-[1.02] transition-all duration-300 shadow cursor-pointer text-sm"
              >
                Download Patient App
                <ArrowRight className="h-4 w-4 ml-2" />
              </button>
            </div>
          </div>
        </div>
      </section>

    </div>
  );
}
